[package]
name = "chip8"
version = "0.1.0"
authors = ["Daniel Luque <53190848+Satore13@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = ""
minifb = "0.11"
argparse = "0.2"
